services:
  obsidian:
    image: lscr.io/linuxserver/obsidian:latest
    container_name: obsidian
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Jerusalem
    volumes:
      - ./config:/config
      - ./vault:/vault
    ports:
      - "3001:3001"
    shm_size: "1gb"
    restart: unless-stopped
